worker_processes auto;
pid /run/nginx.pid;

events {
	worker_connections 768;
}

http {
	include        /etc/nginx/proxy.conf;
        limit_req_zone $binary_remote_addr zone=one:10m rate=5r/s;
        server_tokens  off;

	sendfile on;
	tcp_nopush on;
	tcp_nodelay on;
	keepalive_timeout 65;
	types_hash_max_size 2048;
	
	client_body_timeout 10; client_header_timeout 10; send_timeout 10;

    	upstream algoromida.com{
        	server localhost:5000;
    	}

    	server {
        	listen     80;
        	return     301 https://$host$request_uri;
    	}
	
	include /etc/nginx/mime.types;
	default_type application/octet-stream;

	
	server {
        	listen                    443 ssl;
        	#server_name               algoromida.com www.algoromida.com;
	
		ssl_certificate /etc/letsencrypt/live/algoromida.com/fullchain.pem; # manag$
    		ssl_certificate_key /etc/letsencrypt/live/algoromida.com/privkey.pem; # man$
    		include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    		ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


        	#ssl_protocols             TLSv1.1 TLSv1.2; #specified in: /etc/letsencrypt/options-ssl-nginx.conf
        	#ssl_prefer_server_ciphers on;              #specified in: /etc/letsencrypt/options-ssl-nginx.conf
        	#ssl_ciphers               "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH"; #specified in: /etc/letsencrypt/options-ssl-nginx.conf
        
		ssl_ecdh_curve            secp384r1;
        	ssl_session_cache         shared:SSL:10m;
        	ssl_session_tickets       off;
       		ssl_stapling              on; #ensure your cert is capable
        	ssl_stapling_verify       on; #ensure your cert is capable

		add_header X-Frame-Options "SAMEORIGIN";
        	add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
        	add_header X-Frame-Options DENY;
        	add_header X-Content-Type-Options nosniff;

        	#Redirects all traffic
        	location / {
            		proxy_pass http://algoromida.com;
            		limit_req  zone=one burst=10 nodelay;
        	}
    	}

	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;

	gzip on;
	gzip_disable "msie6";


	include /etc/nginx/conf.d/*.conf;
	include /etc/nginx/sites-enabled/*;
}


